### = Seperates the requests

### Get Car by ID

http://localhost:3005/cars/2

### - Get all Cars

http://localhost:3005/cars

### - Drop table with all Cars

http://localhost:3005/cars/1;DROP TABLE cars;

### Add Shirt

POST http://localhost:3005/shirts HTTP/1.1 
content-type: application/json

{
    "title": "Summer MW 2024",
    "brand": "Quicksilver",
    "des": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga."
}

###before
POST http://localhost:3005/cars HTTP/1.1 
content-type: application/json

{
    "username": "Mercedes C200",
    "bio": "Saloon"
}

### Update Car

PUT http://localhost:3005/cars/1 HTTP/1.1 
content-type: application/json

{
    "username": "Tom",
    "bio": "How are you?"
}

### Delete Car

DELETE http://localhost:3005/cars/1 HTTP/1.1 
content-type: application/json



