### = Seperates the requests

### Get AccountStatus by ID

http://localhost:3005/account-status/32

### - Get all Accountstatus

http://localhost:3005/account-status

### - Drop table with all Accountstatus

http://localhost:3005/account-status/1;DROP TABLE account-status;

### Add AccountStatus 

# POST http://localhost:3005/account-status HTTP/1.1 
# content-type: application/json

# {
#   "user_id": 35,
#   "email": "sample@example.com",
#   "phone_number": "+1234567890",
#   "address_line1": "123 Main Street",
#   "address_line2": "Apt 45",
#   "city": "Sample City",
#   "state": "Sample State",
#   "postal_code": "12345",
#   "country": "Sample Country"
# }
###

# works

POST http://localhost:3005/account-status HTTP/1.1
Content-Type: application/json

{
  "user_id": 32,
  "is_active": true,
  "is_suspended": false,
  "is_deactivated": false,
  "last_login": "2023-12-18T10:22:30"
}




### Update AccountStatus

PUT http://localhost:3005/account-status/32 HTTP/1.1 
content-type: application/json

{
  "user_id": 32,
  "is_active": false,
  "is_suspended": false,
  "is_deactivated": false,
  "last_login": "2023-12-18T10:22:30"
}

### Delete AccountStatus

DELETE http://localhost:3005/account-status/35 HTTP/1.1 
content-type: application/json



