### = Seperates the requests

### Get product by ID

http://localhost:3005/product/3

### - Get all Assets

http://localhost:3005/product

### - Drop table with all Assets

http://localhost:3005/product/1;DROP TABLE product;

### Add product - works

POST http://localhost:3005/product HTTP/1.1
Content-Type: application/json

{
  "ProductName": "Samba",
  "Price": 99.99,
  "Category": "Adidas"
}



### Update product

PUT http://localhost:3005/product/34 HTTP/1.1 
content-type: application/json

{
  "user_id": 34,  
  "bio": "Andreas: ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "date_of_birth": "1985-12-16",
  "location": "Sample location 3",
  "website_url": "http://example3.com",
  "profile_picture_url": "https://upload.wikimedia.org/wikipedia/en/b/b1/Portrait_placeholder.png"
}

### Delete product

DELETE http://localhost:3005/product/35 HTTP/1.1 
content-type: application/json



