### = Seperates the requests

### Get UserPreferences by ID - works

http://localhost:3005/user-preference/32

### - Get all UserPreferences - works

http://localhost:3005/user-preference

### - Drop table with all UserPreferences

http://localhost:3005/user-preferences/1;DROP TABLE userpreferences;

### Add UserPreferences - works

POST http://localhost:3005/user-preferences HTTP/1.1
Content-Type: application/json

{
  "user_id": 41,
  "theme": "dark",
  "language": "english",
  "receive_email_notifications": false,
  "show_online_status": false
}

### Update UserPreferences

# PUT http://localhost:3005/user-preferences/32 HTTP/1.1 
# content-type: application/json

# {
#   "user_id": 32,
#   "is_active": false,
#   "is_suspended": false,
#   "is_deactivated": false,
#   "last_login": "2023-12-18T10:22:30"
# }

PUT http://localhost:3005/user-preference/32 HTTP/1.1
content-type: application/json

{
  "user_id": 32,
  "theme": "dark",
  "language": "english",
  "receive_email_notifications": true,
  "show_online_status": true
  // Add other properties based on the UserPreferences table structure
}

### Delete UserPreferences

DELETE http://localhost:3005/user-preference/32 HTTP/1.1 
content-type: application/json



