### = Seperates the requests

### Get User by ID

http://localhost:3005/users/2

### - Get all Users 

http://localhost:3005/users

### - Drop table with all Users

http://localhost:3005/users/1;DROP TABLE users;

### Add User

POST http://localhost:3005/users HTTP/1.1 
content-type: application/json

{
    "username": "Ywain",
    "bio": "I am a fool?"
}

### Update User

PUT http://localhost:3005/users/1 HTTP/1.1 
content-type: application/json

{
    "username": "Tom",
    "bio": "How are you?"
}

### Delete User

DELETE http://localhost:3005/users/2 HTTP/1.1 
content-type: application/json



